# Generated by Django 5.2.6 on 2025-11-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_log_date_alter_log_id_alter_log_time_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
