# Generated by Django 6.0.7 on 2026-07-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_log_phone_remove_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='card_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_id',
            field=models.BigIntegerField(),
        ),
    ]
